DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
                       USER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
                       LOGIN VARCHAR(30) NOT NULL,
                       PASSWORD VARCHAR(150) NOT NULL,
                       FIRSTNAME VARCHAR(255) NOT NULL,
                       LASTNAME VARCHAR(255),
                       EMAIL VARCHAR(255),
                       CONSTRAINT login_unique UNIQUE (login)
);