From tomcat:8.0.51-jre8-alpine
# expose admin page
USER root
COPY ./hw02-Kubernetes/tomcat/tomcat-users.xml /usr/local/tomcat/conf/
COPY ./hw02-Kubernetes/tomcat/context.xml /usr/local/tomcat/webapps/manager/META-INF/
EXPOSE 8080
RUN rm -fr /usr/local/tomcat/webapps/ROOT
COPY ./hw02-Kubernetes/build/libs/hw02-Kubernetes*.war /usr/local/tomcat/webapps/
CMD ["catalina.sh","run"]

